"""
This is a setup.py script generated by py2applet

Usage:
		python setup.py py2app
"""

from setuptools import setup

APP_NAME = 'Gii'
AUTHOR   = 'Tommo Zhou'
APP = [ 'gii_bin.py' ]
DATA_FILES = []
OPTIONS = {
	'arch': 'i386',
	'argv_emulation': True,
	'optimize': 2,

	'includes': [ 
	'PyQt4', 
	'SocketServer', 
	'watchdog', 
	'watchdog.observers' 
	],
	
	'excludes': [ 'PySide', 'pygame', 'aubio', 'numpy', 'lupa', 'openerp-server', 'wand', 'PIL' ],
	}

setup(
		name           = APP_NAME,
		author         = AUTHOR,
		app            = APP,

		data_files     = DATA_FILES,
		options        = {'py2app': OPTIONS},
		setup_requires = ['py2app']

		# plist = dict(
		# 	CFBundleIdentifier = 'com.hatrix.gii'
		# 	)
)
