"""
This is a setup.py script generated by py2applet

Usage:
		python setup.py py2app
"""

from setuptools import setup
##----------------------------------------------------------------##

APP_NAME = 'Gii'
AUTHOR   = 'Tommo Zhou'
APP = [ 'gii_bin_qt.py' ]
DATA_FILES = []
OPTIONS = {
	'arch': 'x86_64',
	'argv_emulation': True,
	'optimize': 2,
	'strip': False,
	'semi_standalone' : True,
	'use_pythonpath'  : True,
	'emulate_shell_environment' : True,
	# 'includes': [ 
	# 	'sip',
	# 	'PyQt4',
	# 	'PyQt4._qt',
	# 	'PyQt4.QtCore',
	# 	'PyQt4.QtGui',
	# 	'PIL',
	# ],

	# 'excludes': [
	# 	'wx',
	# 	'PyQt4.QtDesigner',
	# 	'PyQt4.QtNetwork',
	# 	'PyQt4.QtScript',
	# 	'PyQt4.QtSql',
	# 	'PyQt4.QtTest',
	# 	'PyQt4.QtXml',
	# 	'PyQt4.phonon'
	#  ],

	}

setup(
		name           = APP_NAME,
		author         = AUTHOR,
		app            = APP,

		data_files     = DATA_FILES,
		options        = {'py2app': OPTIONS},
		setup_requires = ['py2app']

		# plist = dict(
		# 	CFBundleIdentifier = 'com.hatrix.gii'
		# 	)
)
