def options( opt ):
	opt.load( 'compiler_cxx compiler_c' )
	opt.load( 'python' )
	opt.load( 'cython' )

def configure( conf ):
	conf.load( 'compiler_cxx compiler_c' )
	conf.load( 'python' )
	conf.load( 'cython' )

def build( bld ):		
	binPath = bld.env.GII_BINARY_PATH
	import os.path
	if not os.path.exists( binPath + '/python' ):
		os.mkdir( binPath + '/python' )
	output = binPath + '/python'

	#build aku-cython	
	LIBS_SYSTEM = [ 'System', 'crypto', 'ssl', 'objc', 'stdc++' ]

	bld(
		source   = 'AKU.pyx GIIHelper.cpp helpers.cpp',
		features = 'cxx cxxshlib pyext',
		target   = 'AKU.so',
		name     = 'host-python',
		use      = 'MOAI FMOD extension',

		includes = [ '../extension', '/usr/include/python2.7' ],

		framework = [ 
			'CoreServices',
			'CoreFoundation',
			'Foundation',
			'AudioUnit',
			'AudioToolbox',
			'GLUT',
			'IOKit',
			'OpenGL',
			'Python',
		],

		stlib      = LIBS_SYSTEM,
		cxxflags   = [ 
			'-DGLUTHOST_USE_LUAEXT', 
			'-DGLUTHOST_USE_FMOD_DESIGNER' 
		],

		install_path = output
	)



